name: Production Pipe

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: AWS Cli
      run: pip install awscli --upgrade --user
    - name: Install
      run: npm i
    - name: Generate
      run: npm run generate
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy
      run: aws s3 cp dist s3://a55-prd-mxwp --recursive --acl public-read

